[package]
name = "localserver"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1.1.0", features = ["net", "os-poll"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
